
database:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem:mta


server:
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: keystore.jks
      keyStorePassword: mtamta
      keyStoreType: JKS
      supportedProtocols: [TLSv1, TLSv1.1, TLSv1.2, SSLv3]
      validateCerts: false
      validatePeers: false


logging:
  level: INFO
  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/application.log
      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB
